/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Elmar Talibzade
 */
public class BackupsPanel extends javax.swing.JPanel {

    /**
     * Creates new form BackupsPanel
     */
    public BackupsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_backup = new javax.swing.JLabel();
        field_saveLocation = new javax.swing.JTextField();
        label_saveLocation = new javax.swing.JLabel();
        btn_browse_saveLocation = new javax.swing.JButton();
        btn_backup = new javax.swing.JButton();
        label_restore = new javax.swing.JLabel();
        label_backupLocation = new javax.swing.JLabel();
        field_backupLocation = new javax.swing.JTextField();
        btn_browse_backupLocation = new javax.swing.JButton();
        btn_restore = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(706, 398));

        label_backup.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label_backup.setText("Backup");

        label_saveLocation.setText("Export Location");

        btn_browse_saveLocation.setText("Browse...");

        btn_backup.setText("Backup");

        label_restore.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label_restore.setText("Restore");

        label_backupLocation.setText("Backup Location");

        btn_browse_backupLocation.setText("Browse...");

        btn_restore.setText("Restore");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_backup)
                            .addComponent(label_restore))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_saveLocation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(field_saveLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_backupLocation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(field_backupLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_browse_saveLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_browse_backupLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_backup, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(btn_restore, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_backup)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_saveLocation)
                    .addComponent(field_saveLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_browse_saveLocation)
                    .addComponent(btn_backup))
                .addGap(71, 71, 71)
                .addComponent(label_restore)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_backupLocation)
                    .addComponent(field_backupLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_browse_backupLocation)
                    .addComponent(btn_restore))
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_backup;
    private javax.swing.JButton btn_browse_backupLocation;
    private javax.swing.JButton btn_browse_saveLocation;
    private javax.swing.JButton btn_restore;
    private javax.swing.JTextField field_backupLocation;
    private javax.swing.JTextField field_saveLocation;
    private javax.swing.JLabel label_backup;
    private javax.swing.JLabel label_backupLocation;
    private javax.swing.JLabel label_restore;
    private javax.swing.JLabel label_saveLocation;
    // End of variables declaration//GEN-END:variables
}
