/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Staff.*;
import bapers.Utils; 
import javax.swing.JFrame;
/**
 * Identical to StaffView but behaves differently as it's used for accessing controls of another staff member
 * @author Elmar Talibzade
 */
public class ControlledView extends javax.swing.JFrame {

    /**
     * Currently logged user
     */
    private Staff loggedUser;
    
    /**
     * Initializes a GUI and loads appropriate menu items based on user's role.
     * @param user Object class representing a logged in user.
     */
    public ControlledView(Staff user){
        this.loggedUser = user;
        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        initComponents();
        initMenuItems();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_loggedUser = new javax.swing.JLabel();
        btn_disconnect = new javax.swing.JButton();
        tabbedContent = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Accessing Staff Controls - " + loggedUser.getFullName());
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(720, 480));
        setName("Staff View"); // NOI18N
        setSize(new java.awt.Dimension(720, 480));

        label_loggedUser.setText("Accessing: staff-name (staff-role)");

        btn_disconnect.setText("Disconnect");
        btn_disconnect.setFocusable(false);

        tabbedContent.setAlignmentX(0.0F);
        tabbedContent.setAlignmentY(0.0F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbedContent)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_loggedUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 417, Short.MAX_VALUE)
                        .addComponent(btn_disconnect)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_disconnect)
                    .addComponent(label_loggedUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedContent, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initMenuItems() {
        
        label_loggedUser.setText(
                String.format("Accessing: %s (%s%s)", 
                        loggedUser.getFullName(), 
                        Utils.splitCamelCase(loggedUser.getRole().name()),
                        loggedUser.isAssigned() ? " - " + Utils.splitCamelCase(loggedUser.getDepartment().toString()) : ""
                )
        );
    
        switch (loggedUser.getRole())
        {
            case OfficeManager:
                
                tabbedContent.addTab("Receptionists", new ReceptionistBrowserPanel());
                tabbedContent.addTab("Reports", new ReportsManagerPanel());
                tabbedContent.addTab("New Customer", new CreateCustomerPanel());
                tabbedContent.addTab("Customer Browser", new CustomerBrowserPanel());
                tabbedContent.addTab("Job Browser", new JobBrowserPanel());
                tabbedContent.addTab("Staff Browser", new StaffBrowserPanel());
                tabbedContent.addTab("Create Staff", new CreateStaffPanel());
                tabbedContent.addTab("Backups", new BackupsPanel());
                
                break;
            case Receptionist:
                
                tabbedContent.addTab("Customer Browser", new CustomerBrowserPanel());
                tabbedContent.addTab("New Customer", new CreateCustomerPanel());
                tabbedContent.addTab("Job Browser", new JobBrowserPanel());
                
                break;
            case ShiftManager:
                
                tabbedContent.addTab("Receptionists", new ReceptionistBrowserPanel());
                tabbedContent.addTab("Reports", new ReportsManagerPanel());
                tabbedContent.addTab("New Customer", new CreateCustomerPanel());
                tabbedContent.addTab("Customer Browser", new CustomerBrowserPanel());
                tabbedContent.addTab("Job Browser", new JobBrowserPanel());
                
                break;
                
            case Technician:
                
                tabbedContent.addTab("Job Browser", new JobBrowserPanel());
                
                break;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_disconnect;
    private javax.swing.JLabel label_loggedUser;
    private javax.swing.JTabbedPane tabbedContent;
    // End of variables declaration//GEN-END:variables
}