/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Administrator.DBConnectivity;
import Customer.Customer;
import Customer.DepartmentType;
import Customer.DiscountType;
import Staff.Role;
import Staff.Staff;
import static bapers.Bapers.DB;
import javax.swing.JOptionPane;

/**
 *
 * @author Elmar Talibzade
 */
public class CreateStaffPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateStaffPanel
     */
    public CreateStaffPanel() {
        initComponents();
        updateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_firstName = new javax.swing.JLabel();
        field_firstName = new javax.swing.JTextField();
        label_lastName = new javax.swing.JLabel();
        field_lastName = new javax.swing.JTextField();
        label_username = new javax.swing.JLabel();
        field_username = new javax.swing.JTextField();
        label_password = new javax.swing.JLabel();
        field_password = new javax.swing.JPasswordField();
        label_role = new javax.swing.JLabel();
        dropdown_role = new javax.swing.JComboBox<>();
        btn_create = new javax.swing.JButton();
        label_department = new javax.swing.JLabel();
        dropdown_department = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(706, 398));

        label_firstName.setText("First Name");

        label_lastName.setText("Last Name");

        label_username.setText("Username");

        label_password.setText("Password");

        label_role.setText("Role");

        dropdown_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Office Manager", "Shift Manager", "Technician", "Receptionist" }));
        dropdown_role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown_roleActionPerformed(evt);
            }
        });

        btn_create.setText("Create Account");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });

        label_department.setText("Department");

        dropdown_department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Copy Room", "Development", "Finishing", "Packing" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_create))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(label_role)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 73, Short.MAX_VALUE)
                                .addComponent(dropdown_role, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_lastName)
                                    .addComponent(label_firstName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(field_firstName, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(field_lastName))))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_username)
                            .addComponent(label_password)
                            .addComponent(label_department))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(field_username, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(field_password)
                            .addComponent(dropdown_department, 0, 237, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_firstName)
                    .addComponent(field_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_username)
                    .addComponent(field_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_lastName)
                    .addComponent(field_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_password))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_role)
                    .addComponent(dropdown_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropdown_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_department))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(btn_create)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        int accNo = 1;
        String firstName = field_firstName.getText();
        String lastName = field_lastName.getText();
        String username = field_username.getText();
        String password = String.valueOf(field_password.getPassword());
        
        int roleNo = dropdown_role.getSelectedIndex();
        Role role = Role.values()[roleNo];

        Staff newStaff = new Staff(accNo, role, username, firstName, lastName) {};
        
        if (role == Role.Technician)
        {
            newStaff.setDepartment(DepartmentType.values()[dropdown_department.getSelectedIndex()]);
        }
        
        if(bapers.Bapers.DB.createStaff(newStaff, password))
            JOptionPane.showMessageDialog(this, "Staff member created succesfully!",  "SUCCESS", JOptionPane.WARNING_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "An error has occurred while creating a new staff member!",  "ERROR", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btn_createActionPerformed

    private void dropdown_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown_roleActionPerformed
        updateFields();
    }//GEN-LAST:event_dropdown_roleActionPerformed
    
    private void updateFields()
    {
        label_department.setEnabled(dropdown_role.getSelectedIndex() == 2);
        dropdown_department.setEnabled(dropdown_role.getSelectedIndex() == 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.JComboBox<String> dropdown_department;
    private javax.swing.JComboBox<String> dropdown_role;
    private javax.swing.JTextField field_firstName;
    private javax.swing.JTextField field_lastName;
    private javax.swing.JPasswordField field_password;
    private javax.swing.JTextField field_username;
    private javax.swing.JLabel label_department;
    private javax.swing.JLabel label_firstName;
    private javax.swing.JLabel label_lastName;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_role;
    private javax.swing.JLabel label_username;
    // End of variables declaration//GEN-END:variables
}
