/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import Administrator.DBConnectivity;
import Customer.Customer;
import bapers.Bapers;
import javax.swing.JOptionPane;

/**
 *
 * @author mihaimatraguna
 */
public class CreateCustomerUI extends javax.swing.JFrame {

    /** Creates new form CreateCustomerUI */
    public CreateCustomerUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createJobsButton = new javax.swing.JButton();
        createCustomerButton = new javax.swing.JButton();
        label_loggedUser = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        label_accountNo = new javax.swing.JLabel();
        input_accNo = new javax.swing.JTextField();
        label_holderName = new javax.swing.JLabel();
        input_holderName = new javax.swing.JTextField();
        label_firstName = new javax.swing.JLabel();
        input_firstName = new javax.swing.JTextField();
        label_lastName = new javax.swing.JLabel();
        input_lastName = new javax.swing.JTextField();
        label_phone = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        bttn_createCustomer = new javax.swing.JButton();
        input_email = new javax.swing.JTextField();
        input_phone = new javax.swing.JTextField();
        label_address = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createJobsButton.setText("Create Job");

        createCustomerButton.setText("Create Customer");

        label_loggedUser.setText("Logged in as: {name}");

        btn_logout.setText("Log Out");

        label_accountNo.setText("Account No: ");

        input_accNo.setText("00");
        input_accNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_accNoActionPerformed(evt);
            }
        });

        label_holderName.setText("Holder Name: ");

        input_holderName.setText("Name");
        input_holderName.setToolTipText("");
        input_holderName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_holderNameActionPerformed(evt);
            }
        });

        label_firstName.setText("First Name:");

        input_firstName.setText("John");

        label_lastName.setText("Last Name:");

        input_lastName.setText("Wood");

        label_phone.setText("Phone Number:");

        label_email.setText("Email:");

        bttn_createCustomer.setText("Create Customer");
        bttn_createCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_createCustomerActionPerformed(evt);
            }
        });

        input_email.setText("email@mail.com");

        label_address.setText("Address:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(createCustomerButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createJobsButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_loggedUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(105, 105, 105)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 446, Short.MAX_VALUE)
                        .addComponent(btn_logout))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_firstName)
                                    .addComponent(label_lastName)
                                    .addComponent(label_email)
                                    .addComponent(label_holderName)
                                    .addComponent(label_accountNo))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(input_lastName)
                                    .addComponent(input_firstName)
                                    .addComponent(input_holderName)
                                    .addComponent(input_accNo)
                                    .addComponent(input_email, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(label_phone))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(label_address)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2)
                                    .addComponent(input_phone)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bttn_createCustomer)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_loggedUser)
                    .addComponent(btn_logout))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createJobsButton)
                    .addComponent(createCustomerButton))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_accountNo)
                            .addComponent(input_accNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_address))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_holderName)
                            .addComponent(input_holderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_firstName)
                            .addComponent(input_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(input_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_lastName)
                            .addComponent(label_phone)
                            .addComponent(input_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(input_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(bttn_createCustomer))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_accNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_accNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_accNoActionPerformed

    private void input_holderNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_holderNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_holderNameActionPerformed

    private void bttn_createCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_createCustomerActionPerformed
            
    }//GEN-LAST:event_bttn_createCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateCustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateCustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateCustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateCustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateCustomerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton bttn_createCustomer;
    private javax.swing.JButton createCustomerButton;
    private javax.swing.JButton createJobsButton;
    private javax.swing.JTextField input_accNo;
    private javax.swing.JTextField input_email;
    private javax.swing.JTextField input_firstName;
    private javax.swing.JTextField input_holderName;
    private javax.swing.JTextField input_lastName;
    private javax.swing.JTextField input_phone;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel label_accountNo;
    private javax.swing.JLabel label_address;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_firstName;
    private javax.swing.JLabel label_holderName;
    private javax.swing.JLabel label_lastName;
    private javax.swing.JLabel label_loggedUser;
    private javax.swing.JLabel label_phone;
    // End of variables declaration//GEN-END:variables

}
