/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Customer.*;
import Staff.Role;
import static bapers.Bapers.DB;
import bapers.Utils;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 * GUI for displaying Customer's information as well as jobs
 * @author Elmar Talibzade
 */
public class CustomerProfilePanel extends javax.swing.JPanel {

    private Customer customer;
    private AccountSettingsView accountSettingsView;
    private CustomerBrowserPanel customerBrowser;
    
    /**
     * Creates new form CustomerProfilePanel
     * @param customerBrowser parent customer browser object
     */
    public CustomerProfilePanel(CustomerBrowserPanel customerBrowser) {
        initComponents();
        this.customerBrowser = customerBrowser;
    }
    
    /**
     * Changes customer's info to another customer and updates the GUI
     * @param customer new customer whose data would be displayed
     */
    public void setCustomer(Customer customer)
    {
        this.customer = customer;
        updateGUI();
    }
    
    private void updateGUI()
    {
        label_fullName.setText(String.format("%s %s", customer.getFirstName(), customer.getLastName()));
        label_accountNo.setText(String.format("ACC%03d", customer.getAccountNo()));
        label_holderName.setText("Holder Name: " + customer.getHolderName());
        label_email.setText("Email: " + customer.getEmailAddress());
        label_phone.setText("Phone Number: " + customer.getPhoneNumber());
        label_address.setText("Address: " + customer.getAddress());
        label_discountType.setText("Discount Type: " + Utils.splitCamelCase(customer.getAgreedDiscount().toString()));
        
        int cardNumber = customer.getLast4Digit();
        String cardLabel = DB.isCardInserted(customer.getAccountNo()) ? "Card ending in " + cardNumber : "Cash";
        label_paymentType.setText("Payment Type: " + cardLabel);
        
        label_stat_inDefault.setVisible(customer.isDefault());
        label_stat_suspended.setVisible(customer.isSuspended());
        label_stat_valued.setVisible(customer.isValued());        
        
        btn_createJob.setEnabled(!customer.isSuspended());
        
        btn_reactivate.setVisible(customer.isDefault() && DB.loggedUser.getRole() == Role.OfficeManager);
        
        updateTable();   
    }
    
    private void updateTable()
    {
        DefaultTableModel model = (DefaultTableModel)table_tasks.getModel();
        
        while (model.getRowCount() > 0)
        {
            model.removeRow(0);
        }
        
        for (Job job : customer.getJobs())
        {
            for (Task task : job.getTasks())
            {
                model.addRow(new Object[] {job.getCode(), task.getId(), task.getDepartment(), task.getStartTime(), task.getDescription()});
            }
        }
    }
    
    private void addListener(CreateJobView jobView)
    {
        jobView.btn_create.addActionListener((java.awt.event.ActionEvent evt) -> {
            CreateJob(jobView.getJob());
            jobView.dispose();
            updateGUI();
        });
    }
    
    private void addListener(AccountSettingsView accountSettings)
    {        
        accountSettings.btn_deleteAccount.addActionListener((java.awt.event.ActionEvent evt) -> {
            deleteCustomer();
        });
    }
    
    private void deleteCustomer()
    {
        int dialogResult = JOptionPane.showConfirmDialog(null, 
                String.format("This action cannot be undone! Are you sure you would like to delete the following customer\n%s", customer.getFullName()), 
                "Attention!", 
                JOptionPane.YES_OPTION);
        
        if (dialogResult != JOptionPane.YES_OPTION) return;
        
        accountSettingsView.dispose();
        customerBrowser.deleteCustomer(customer);
    }
    
    private void CreateJob(Job newJob)
    {
        customer.getJobs().add(newJob);
        DB.createJob(newJob);
    }
    
    private void reactivateAccount()
    {
        int dialogResult = JOptionPane.showConfirmDialog(null, 
                String.format("You're about to reactivate customer's account.\n\n%s\n\nProceed?", customer.getFullName()), 
                "Warning!", 
                JOptionPane.YES_OPTION);
        
        if (dialogResult != JOptionPane.YES_OPTION) return;
        DB.reactivateCustomerAccount(customer.getAccountNo());
        customer.setIsDefault(false);
        updateGUI();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label_fullName = new javax.swing.JLabel();
        label_accountNo = new javax.swing.JLabel();
        label_holderName = new javax.swing.JLabel();
        label_email = new javax.swing.JLabel();
        label_phone = new javax.swing.JLabel();
        label_discountType = new javax.swing.JLabel();
        table_jobs = new javax.swing.JScrollPane();
        table_tasks = new javax.swing.JTable();
        btn_back = new javax.swing.JButton();
        pane_generalStats = new javax.swing.JPanel();
        label_stat_suspended = new javax.swing.JLabel();
        label_stat_inDefault = new javax.swing.JLabel();
        label_stat_valued = new javax.swing.JLabel();
        label_paymentType = new javax.swing.JLabel();
        pane_buttons = new javax.swing.JPanel();
        btn_reactivate = new javax.swing.JButton();
        btn_editAccount = new javax.swing.JButton();
        btn_setPayment = new javax.swing.JButton();
        btn_createJob = new javax.swing.JButton();
        label_address = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setPreferredSize(new java.awt.Dimension(706, 398));

        label_fullName.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label_fullName.setText("{Customer-Full-Name}");

        label_accountNo.setText("{account-number}");

        label_holderName.setText("Holder Name: {holder-name}");

        label_email.setText("Email: {email}");

        label_phone.setText("Phone Number: {phone-number}");

        label_discountType.setText("Discount Type: {discount-type}");

        table_tasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job Code", "Task ID", "Department", "Time Started", "Special Instructions"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_jobs.setViewportView(table_tasks);

        btn_back.setText("Back");
        btn_back.setMaximumSize(new java.awt.Dimension(92, 32));
        btn_back.setMinimumSize(new java.awt.Dimension(92, 32));

        label_stat_suspended.setForeground(new java.awt.Color(255, 51, 51));
        label_stat_suspended.setText("Suspended");

        label_stat_inDefault.setText("In Default");

        label_stat_valued.setBackground(new java.awt.Color(0, 51, 255));
        label_stat_valued.setForeground(new java.awt.Color(0, 153, 204));
        label_stat_valued.setText("Valued");

        javax.swing.GroupLayout pane_generalStatsLayout = new javax.swing.GroupLayout(pane_generalStats);
        pane_generalStats.setLayout(pane_generalStatsLayout);
        pane_generalStatsLayout.setHorizontalGroup(
            pane_generalStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_generalStatsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_stat_valued)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_stat_suspended)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_stat_inDefault)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pane_generalStatsLayout.setVerticalGroup(
            pane_generalStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_generalStatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pane_generalStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_stat_valued)
                    .addComponent(label_stat_suspended)
                    .addComponent(label_stat_inDefault))
                .addContainerGap())
        );

        label_paymentType.setText("Payment Type: {payment-type}");

        pane_buttons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btn_reactivate.setText("Reactivate");
        btn_reactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reactivateActionPerformed(evt);
            }
        });
        pane_buttons.add(btn_reactivate);

        btn_editAccount.setText("Edit Account...");
        btn_editAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editAccountActionPerformed(evt);
            }
        });
        pane_buttons.add(btn_editAccount);

        btn_setPayment.setText("Invoices");
        btn_setPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setPaymentActionPerformed(evt);
            }
        });
        pane_buttons.add(btn_setPayment);

        btn_createJob.setText("Create Job");
        btn_createJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createJobActionPerformed(evt);
            }
        });
        pane_buttons.add(btn_createJob);

        label_address.setText("Address: {address}");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(table_jobs)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_accountNo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_holderName)
                                    .addComponent(label_phone)
                                    .addComponent(label_email))
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_address)
                                    .addComponent(label_discountType)
                                    .addComponent(label_paymentType, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 222, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_fullName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pane_generalStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pane_buttons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_fullName)
                    .addComponent(pane_generalStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(label_accountNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_holderName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_discountType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_paymentType)
                    .addComponent(label_phone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_email)
                    .addComponent(label_address))
                .addGap(20, 20, 20)
                .addComponent(pane_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(table_jobs, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_setPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setPaymentActionPerformed
        InvoicesView invoicesView = new InvoicesView((JFrame) SwingUtilities.getWindowAncestor(this), true, customer);
        invoicesView.setVisible(true);
    }//GEN-LAST:event_btn_setPaymentActionPerformed

    private void btn_createJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createJobActionPerformed
        CreateJobView createJobView = new CreateJobView((JFrame) SwingUtilities.getWindowAncestor(this), true, customer.getAccountNo());
        addListener(createJobView);
        createJobView.setVisible(true);
    }//GEN-LAST:event_btn_createJobActionPerformed

    private void btn_editAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editAccountActionPerformed
        //NOT WORKING YET!
        accountSettingsView = new AccountSettingsView((JFrame) SwingUtilities.getWindowAncestor(this), true, this, customer);
        addListener(accountSettingsView);
        accountSettingsView.setVisible(true);
    }//GEN-LAST:event_btn_editAccountActionPerformed

    private void btn_reactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reactivateActionPerformed
        reactivateAccount();
    }//GEN-LAST:event_btn_reactivateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_back;
    private javax.swing.JButton btn_createJob;
    private javax.swing.JButton btn_editAccount;
    private javax.swing.JButton btn_reactivate;
    private javax.swing.JButton btn_setPayment;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_accountNo;
    private javax.swing.JLabel label_address;
    private javax.swing.JLabel label_discountType;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_fullName;
    private javax.swing.JLabel label_holderName;
    private javax.swing.JLabel label_paymentType;
    private javax.swing.JLabel label_phone;
    private javax.swing.JLabel label_stat_inDefault;
    private javax.swing.JLabel label_stat_suspended;
    private javax.swing.JLabel label_stat_valued;
    private javax.swing.JPanel pane_buttons;
    private javax.swing.JPanel pane_generalStats;
    private javax.swing.JScrollPane table_jobs;
    private javax.swing.JTable table_tasks;
    // End of variables declaration//GEN-END:variables
}
