/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Customer.Customer;
import Customer.Task;
import Payment.Invoice;
import static bapers.Bapers.DB;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elmar Talibzade
 */
public class InvoicesView extends javax.swing.JDialog {
    
    private ArrayList<Invoice> invoices;
    private Customer customer;

    private InvoicePanel pane_invoicePanel;
    private CardLayout cardLayout;

    
    /**
     * Creates new form InvoicesView
     */
    public InvoicesView(java.awt.Frame parent, boolean modal, Customer customer) {
        super(parent, modal);
        this.setLocationRelativeTo(null);
        
        this.customer = customer;
        initComponents();
        initCardLayout();
        addListener();
        getInvoices();
    }

    private void initCardLayout()
    {
        pane_invoicePanel = new InvoicePanel(customer);
        card.setLayout(new CardLayout());
        cardLayout = (CardLayout)card.getLayout();
        card.add(pane_invoicePanel, "profile");
        card.add(pane_invoicesList, "browser");
        cardLayout.show(card, "browser");
    }

    private void toggleProfile(boolean state)
    {
        String cardName = state ? "profile" : "browser";
        cardLayout.show(card, cardName);   
        
        this.validate();
        this.repaint();
    }
    
    private void addListener()
    {
        pane_invoicePanel.btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleProfile(false);
                getInvoices();
            }
        });
    }
    
    private void updateGUI()
    {
        label_customerInfo.setText(String.format("Viewing: %s (%s)", 
                customer.getFullName(), 
                String.format("ACC%03d", customer.getAccountNo())
        ));
        
        updateTable();
    }
    
    private void updateTable()
    {
       DefaultTableModel model = (DefaultTableModel)table_invoices.getModel();
       
        while (model.getRowCount() > 0)
        {
            model.removeRow(0);
        }
        
        for (Invoice invoice : invoices)
        {
            model.addRow(new Object[] {
                invoice.getInvoiceNo(),
                new DecimalFormat("£0.00").format(invoice.getSubTotal()),
                invoice.getDiscountRate(),
                new SimpleDateFormat("dd/MM/yyyy HH:mm").format(invoice.getDateCreated()),
                invoice.getDatePaid() != null ? new SimpleDateFormat("dd/MM/yyyy HH:mm").format(invoice.getDatePaid()) : "Never"
            });
        }
    }
    
    private void getInvoices()
    {
       invoices = DB.getInvoices(customer.getAccountNo());
       updateGUI();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_customerInfo = new javax.swing.JLabel();
        card = new javax.swing.JPanel();
        pane_invoicesList = new javax.swing.JPanel();
        btn_generateInvoice = new javax.swing.JButton();
        pane_invoices = new javax.swing.JScrollPane();
        table_invoices = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer Invoices");
        setPreferredSize(new java.awt.Dimension(465, 503));
        setResizable(false);
        setSize(new java.awt.Dimension(465, 503));

        label_customerInfo.setText("Viewing: {customer-name} ({account-no})");

        btn_generateInvoice.setText("Generate New");
        btn_generateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generateInvoiceActionPerformed(evt);
            }
        });

        table_invoices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice No", "Subtotal", "Discount Rate", "Date Created", "Date Paid"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_invoices.getTableHeader().setReorderingAllowed(false);
        table_invoices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_invoicesMouseClicked(evt);
            }
        });
        pane_invoices.setViewportView(table_invoices);
        if (table_invoices.getColumnModel().getColumnCount() > 0) {
            table_invoices.getColumnModel().getColumn(0).setResizable(false);
            table_invoices.getColumnModel().getColumn(1).setResizable(false);
            table_invoices.getColumnModel().getColumn(2).setResizable(false);
            table_invoices.getColumnModel().getColumn(3).setResizable(false);
            table_invoices.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout pane_invoicesListLayout = new javax.swing.GroupLayout(pane_invoicesList);
        pane_invoicesList.setLayout(pane_invoicesListLayout);
        pane_invoicesListLayout.setHorizontalGroup(
            pane_invoicesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_invoicesListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pane_invoicesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pane_invoices)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_invoicesListLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_generateInvoice)))
                .addContainerGap())
        );
        pane_invoicesListLayout.setVerticalGroup(
            pane_invoicesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_invoicesListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_generateInvoice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pane_invoices)
                .addContainerGap())
        );

        javax.swing.GroupLayout cardLayout = new javax.swing.GroupLayout(card);
        card.setLayout(cardLayout);
        cardLayout.setHorizontalGroup(
            cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pane_invoicesList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        cardLayout.setVerticalGroup(
            cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pane_invoicesList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_customerInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(card, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(label_customerInfo)
                .addGap(12, 12, 12)
                .addComponent(card, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_generateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generateInvoiceActionPerformed
        DB.generateInvoiceForJobs(customer);
        getInvoices();
    }//GEN-LAST:event_btn_generateInvoiceActionPerformed

    private void table_invoicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_invoicesMouseClicked
        if (evt.getClickCount() == 2)
        {
            JTable targetTable = (JTable)evt.getSource();
            Invoice invoice = invoices.get(targetTable.getSelectedRow());
            pane_invoicePanel.setInvoice(invoice);
            toggleProfile(true);
        }
    }//GEN-LAST:event_table_invoicesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_generateInvoice;
    private javax.swing.JPanel card;
    private javax.swing.JLabel label_customerInfo;
    private javax.swing.JScrollPane pane_invoices;
    private javax.swing.JPanel pane_invoicesList;
    private javax.swing.JTable table_invoices;
    // End of variables declaration//GEN-END:variables
}
