/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Customer.*;
import java.awt.CardLayout;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * Used to browse tasks and opens the task overview panel
 * @author Elmar Talibzade
 */
public class JobBrowserPanel extends javax.swing.JPanel {

    private ArrayList<Task> tasks;
    
    private TaskProfilePanel pane_taskProfile;
    private CardLayout cardLayout;
    
    /**
     * Creates new form JobBrowser and creates associated layouts.
     */
    public JobBrowserPanel() {
        initComponents();
        initCardLayout();
        addListener();
        getTasks();
    }

    private void initCardLayout()
    {
        pane_taskProfile = new TaskProfilePanel();
        card.setLayout(new CardLayout());
        cardLayout = (CardLayout)card.getLayout();
        card.add(pane_taskProfile, "profile");
        card.add(pane_taskBrowser, "browser");
        cardLayout.show(card, "browser");
    }
    
    private void addListener()
    {
        pane_taskProfile.btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleProfile(false);
                getTasks();
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        card = new javax.swing.JPanel();
        pane_taskBrowser = new javax.swing.JPanel();
        label_jobCode = new javax.swing.JLabel();
        field_jobCode = new javax.swing.JTextField();
        label_status = new javax.swing.JLabel();
        dropdown_jobStatus = new javax.swing.JComboBox<>();
        label_shelfNo = new javax.swing.JLabel();
        field_shelfNo = new javax.swing.JTextField();
        label_department = new javax.swing.JLabel();
        dropdown_department = new javax.swing.JComboBox<>();
        btn_findJob = new javax.swing.JButton();
        table = new javax.swing.JScrollPane();
        table_tasks = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setPreferredSize(new java.awt.Dimension(706, 398));

        label_jobCode.setText("Job Code");

        field_jobCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_jobCodeActionPerformed(evt);
            }
        });

        label_status.setText("Status");

        dropdown_jobStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any", "Inactive", "In Progress", "Completed" }));
        dropdown_jobStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown_jobStatusActionPerformed(evt);
            }
        });

        label_shelfNo.setText("Shelf No");

        field_shelfNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_shelfNoActionPerformed(evt);
            }
        });

        label_department.setText("Department");

        dropdown_department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any", "Copy Room", "Development", "Finishing Room", "Packing" }));
        dropdown_department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown_departmentActionPerformed(evt);
            }
        });

        btn_findJob.setText("Find Job");
        btn_findJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findJobActionPerformed(evt);
            }
        });

        table_tasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job Code", "Task ID", "Department", "Shelf No", "Date Created", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_tasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_tasksMouseClicked(evt);
            }
        });
        table.setViewportView(table_tasks);

        javax.swing.GroupLayout pane_taskBrowserLayout = new javax.swing.GroupLayout(pane_taskBrowser);
        pane_taskBrowser.setLayout(pane_taskBrowserLayout);
        pane_taskBrowserLayout.setHorizontalGroup(
            pane_taskBrowserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_taskBrowserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pane_taskBrowserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_taskBrowserLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_findJob))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane_taskBrowserLayout.createSequentialGroup()
                        .addGroup(pane_taskBrowserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(field_jobCode)
                            .addComponent(label_jobCode))
                        .addGap(35, 35, 35)
                        .addGroup(pane_taskBrowserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dropdown_jobStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_status))
                        .addGap(35, 35, 35)
                        .addGroup(pane_taskBrowserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(field_shelfNo)
                            .addComponent(label_shelfNo))
                        .addGap(35, 35, 35)
                        .addGroup(pane_taskBrowserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dropdown_department, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_department)))
                    .addComponent(table, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pane_taskBrowserLayout.setVerticalGroup(
            pane_taskBrowserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_taskBrowserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pane_taskBrowserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_jobCode)
                    .addComponent(label_status)
                    .addComponent(label_shelfNo)
                    .addComponent(label_department))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pane_taskBrowserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_jobCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropdown_jobStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_shelfNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropdown_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_findJob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(table)
                .addContainerGap())
        );

        javax.swing.GroupLayout cardLayout = new javax.swing.GroupLayout(card);
        card.setLayout(cardLayout);
        cardLayout.setHorizontalGroup(
            cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane_taskBrowser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cardLayout.setVerticalGroup(
            cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane_taskBrowser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(card, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(card, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_findJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findJobActionPerformed
        getTasks();
    }//GEN-LAST:event_btn_findJobActionPerformed

    private void field_jobCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_jobCodeActionPerformed
        getTasks();
    }//GEN-LAST:event_field_jobCodeActionPerformed

    private void dropdown_jobStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown_jobStatusActionPerformed
        getTasks();
    }//GEN-LAST:event_dropdown_jobStatusActionPerformed

    private void field_shelfNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_shelfNoActionPerformed
        getTasks();
    }//GEN-LAST:event_field_shelfNoActionPerformed

    private void dropdown_departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown_departmentActionPerformed
        getTasks();
    }//GEN-LAST:event_dropdown_departmentActionPerformed

    private void table_tasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_tasksMouseClicked
        if (evt.getClickCount() == 2)
        {
            JTable targetTable = (JTable)evt.getSource();
            Task task = tasks.get(targetTable.getSelectedRow());
            pane_taskProfile.setTask(task);
            toggleProfile(true);
        }
    }//GEN-LAST:event_table_tasksMouseClicked

    private void getTasks()
    {
        ArrayList<Job> jobs = bapers.Bapers.DB.getJobs(
                field_jobCode.getText(),
                (dropdown_jobStatus.getSelectedIndex() == 0) ? 9 : dropdown_jobStatus.getSelectedIndex(),
                field_shelfNo.getText(),
                (dropdown_department.getSelectedIndex() == 0) ? 9 : dropdown_department.getSelectedIndex()
        );
        
        tasks = new ArrayList<Task>();
        
        for (Job job : jobs)
        {
            tasks.addAll(job.getTasks());
        }
        
        updateTable();
    }
    
    private void updateTable()
    {
       DefaultTableModel model = (DefaultTableModel)table_tasks.getModel();
       
        while (model.getRowCount() > 0)
        {
            model.removeRow(0);
        }
        
        for (Task task : tasks)
        {
            model.addRow(new Object[]{

                task.getJobCode(),
                task.getId(),
                bapers.Utils.splitCamelCase(task.getDepartment().toString()),
                task.getShelfSlot(),
                "NULL",
                bapers.Utils.splitCamelCase(task.getStatus().toString())

            });
        }
    }

    private void toggleProfile(boolean state)
    {
        String cardName = state ? "profile" : "browser";
        cardLayout.show(card, cardName);   
        
        this.validate();
        this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_findJob;
    private javax.swing.JPanel card;
    private javax.swing.JComboBox<String> dropdown_department;
    private javax.swing.JComboBox<String> dropdown_jobStatus;
    private javax.swing.JTextField field_jobCode;
    private javax.swing.JTextField field_shelfNo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel label_department;
    private javax.swing.JLabel label_jobCode;
    private javax.swing.JLabel label_shelfNo;
    private javax.swing.JLabel label_status;
    private javax.swing.JPanel pane_taskBrowser;
    private javax.swing.JScrollPane table;
    private javax.swing.JTable table_tasks;
    // End of variables declaration//GEN-END:variables
}