/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Elmar Talibzade
 */
public class ReceptionistBrowserPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReceptionistBrowserPanel
     */
    public ReceptionistBrowserPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_receptionistId = new javax.swing.JLabel();
        field_receptionistId = new javax.swing.JTextField();
        btn_accessControls = new javax.swing.JButton();
        table_receptionists = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label_receptionists = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(706, 398));

        label_receptionistId.setText("Receptionist ID");

        btn_accessControls.setText("Access Controls");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Receptionist Name", "Is Absent"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_receptionists.setViewportView(jTable1);

        label_receptionists.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label_receptionists.setText("Receptionists");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(table_receptionists)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_receptionistId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(field_receptionistId, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_accessControls))
                            .addComponent(label_receptionists))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_receptionistId)
                    .addComponent(field_receptionistId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_accessControls))
                .addGap(27, 27, 27)
                .addComponent(label_receptionists)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(table_receptionists)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accessControls;
    private javax.swing.JTextField field_receptionistId;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_receptionistId;
    private javax.swing.JLabel label_receptionists;
    private javax.swing.JScrollPane table_receptionists;
    // End of variables declaration//GEN-END:variables
}
