/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Report.ReportWizard;

/**
 *
 * @author Elmar Talibzade
 */
public class ReportsManagerPanel extends javax.swing.JPanel {

    private boolean canGenerate = true;
    
    /**
     * Creates new form ReportsManagerPanel
     */
    public ReportsManagerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        label_generateReport = new javax.swing.JLabel();
        label_reportType = new javax.swing.JLabel();
        dropdown_reportType = new javax.swing.JComboBox<>();
        label_accountNO = new javax.swing.JLabel();
        field_accountNO = new javax.swing.JTextField();
        btn_generateReport = new javax.swing.JButton();
        label_dateStart = new javax.swing.JLabel();
        label_dateEnd = new javax.swing.JLabel();
        label_reportSettings = new javax.swing.JLabel();
        label_frequency = new javax.swing.JLabel();
        dropdown_timing = new javax.swing.JComboBox<>();
        field_timing = new javax.swing.JTextField();
        label_frequencyTiming = new javax.swing.JLabel();
        btn_saveSettings = new javax.swing.JButton();
        date_reportStart = new org.jdesktop.swingx.JXDatePicker();
        date_reportEnd = new org.jdesktop.swingx.JXDatePicker();
        checkbox_openOnceDone = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(706, 398));

        label_generateReport.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label_generateReport.setText("Generate Report");

        label_reportType.setText("Type");

        dropdown_reportType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer Report", "Individual Performance Report", "Summary Performance Report" }));
        dropdown_reportType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown_reportTypeActionPerformed(evt);
            }
        });

        label_accountNO.setText("Customer Account NO");

        btn_generateReport.setText("Generate");
        btn_generateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generateReportActionPerformed(evt);
            }
        });

        label_dateStart.setText("Start");

        label_dateEnd.setText("End");

        label_reportSettings.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label_reportSettings.setText("Report Settings");

        label_frequency.setText("Frequency");

        dropdown_timing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minute", "Hour", "Day", "Week", "Month", "Year" }));

        label_frequencyTiming.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_frequencyTiming.setText("Report is generated every {time} {frequency}.");

        btn_saveSettings.setText("Save Changes");

        checkbox_openOnceDone.setText("Open After Completion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_accountNO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(field_accountNO))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_reportType)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(dropdown_reportType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(label_dateStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date_reportStart, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_dateEnd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date_reportEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_generateReport)
                            .addComponent(label_frequency)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dropdown_timing, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(field_timing, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label_frequencyTiming))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_saveSettings))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_reportSettings)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(checkbox_openOnceDone)
                                .addGap(6, 6, 6)))
                        .addComponent(btn_generateReport)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_generateReport)
                .addGap(18, 18, 18)
                .addComponent(label_reportType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropdown_reportType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_dateStart)
                    .addComponent(date_reportStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_dateEnd)
                    .addComponent(date_reportEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_accountNO)
                    .addComponent(field_accountNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_generateReport)
                    .addComponent(checkbox_openOnceDone))
                .addGap(1, 1, 1)
                .addComponent(label_reportSettings)
                .addGap(18, 18, 18)
                .addComponent(label_frequency)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropdown_timing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_timing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(label_frequencyTiming)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_saveSettings)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_generateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generateReportActionPerformed
        GenerateReport();
    }//GEN-LAST:event_btn_generateReportActionPerformed

    private void dropdown_reportTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown_reportTypeActionPerformed
        label_accountNO.setEnabled(dropdown_reportType.getSelectedIndex() == 0);
        field_accountNO.setEnabled(dropdown_reportType.getSelectedIndex() == 0);
    }//GEN-LAST:event_dropdown_reportTypeActionPerformed

    private void GenerateReport()
    {
        if (!canGenerate) return;
        toggleReportFunctionality(false);
        
        String reportPath = "";
        
        switch (dropdown_reportType.getSelectedIndex())
        {
            case 0:
                
                // Customer Report
                
                break;
                
            case 1:
                
                // Individual Performance Report
                reportPath = Report.ReportWizard.GenerateIndividualPerformanceReport(date_reportStart.getDate(), date_reportEnd.getDate());
                
                break;
                
            case 2:
                
                // Summary Performance Report
                reportPath = Report.ReportWizard.GenerateSummaryPerformanceReport(date_reportStart.getDate(), date_reportEnd.getDate());
                
                break;
                
            default:
                reportPath = null;
                break;
        }
        
        toggleReportFunctionality(true);
        
        if (!checkbox_openOnceDone.isSelected()) return;
        
        if (reportPath != null)
        {
            ReportWizard.OpenPDF(reportPath);
        }
    }
    
    private void toggleReportFunctionality(boolean enabled)
    {
        if (enabled)
        {
            btn_generateReport.setText("Generate");
        }
        else
        {
            btn_generateReport.setText("Please Wait");
        }
        
        btn_generateReport.setEnabled(enabled);
        canGenerate = enabled;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_generateReport;
    private javax.swing.JButton btn_saveSettings;
    private javax.swing.JCheckBox checkbox_openOnceDone;
    private org.jdesktop.swingx.JXDatePicker date_reportEnd;
    private org.jdesktop.swingx.JXDatePicker date_reportStart;
    private javax.swing.JComboBox<String> dropdown_reportType;
    private javax.swing.JComboBox<String> dropdown_timing;
    private javax.swing.JTextField field_accountNO;
    private javax.swing.JTextField field_timing;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JLabel label_accountNO;
    private javax.swing.JLabel label_dateEnd;
    private javax.swing.JLabel label_dateStart;
    private javax.swing.JLabel label_frequency;
    private javax.swing.JLabel label_frequencyTiming;
    private javax.swing.JLabel label_generateReport;
    private javax.swing.JLabel label_reportSettings;
    private javax.swing.JLabel label_reportType;
    // End of variables declaration//GEN-END:variables
}
