/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Customer.*;
import Staff.Role;
import bapers.Bapers;
/**
 * Task Profile
 * @author Elmar Talibzade
 */
public class TaskProfilePanel extends javax.swing.JPanel {

    private Task task;
    
    /**
     * Creates new form TaskProfilePanel
     */
    public TaskProfilePanel() {
        initComponents();
        
        field_description.setEnabled(Bapers.getUser().getRole() != Role.Receptionist);
        dropdown_department.setEnabled(Bapers.getUser().getRole() != Role.Receptionist);
        dropdown_status.setEnabled(Bapers.getUser().getRole() != Role.Receptionist);
        btn_applyChanges.setVisible(Bapers.getUser().getRole() != Role.Receptionist);
    }

    /**
     * Makes this panel display info of a new task
     * @param task Tasks whose info will be displayed
     */
    public void setTask(Task task)
    {
        this.task = task;
        updateGUI();
    }
    
    private void updateGUI()
    {
        label_jobCode.setText("Job Code: " + task.getJobCode());
        label_taskId.setText("Task ID: " + task.getId());
        label_taskPrice.setText("Price: " + task.getPrice());
        label_shelfNo.setText("Shelf NO: " + task.getShelfSlot());
        field_description.setText(task.getDescription());
        dropdown_department.setSelectedIndex(task.getDepartment().ordinal());
        dropdown_status.setSelectedIndex(task.getStatus().ordinal());
    }
    
    private void submitChanges() {
        task.setDescription(field_description.getText());
        task.setDepartment(DepartmentType.values()[dropdown_department.getSelectedIndex()]);
        task.setStatus(Status.values()[dropdown_status.getSelectedIndex()]);
        bapers.Bapers.DB.updateTask(task);
        updateGUI();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_jobCode = new javax.swing.JLabel();
        label_timeStarted = new javax.swing.JLabel();
        label_taskId = new javax.swing.JLabel();
        label_shelfNo = new javax.swing.JLabel();
        label_description = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        field_description = new javax.swing.JTextArea();
        label_status = new javax.swing.JLabel();
        dropdown_status = new javax.swing.JComboBox<>();
        label_department = new javax.swing.JLabel();
        dropdown_department = new javax.swing.JComboBox<>();
        label_taskPrice = new javax.swing.JLabel();
        btn_applyChanges = new javax.swing.JButton();
        btn_resetFields = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(706, 398));

        label_jobCode.setText("Job Code: {job-code}");

        label_timeStarted.setText("Time Started: {start-time}");

        label_taskId.setText("Task ID: {task-id}");

        label_shelfNo.setText("Shelf NO: {shelf-no}");

        label_description.setText("Description");

        field_description.setColumns(20);
        field_description.setRows(5);
        jScrollPane1.setViewportView(field_description);

        label_status.setText("Status");

        dropdown_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unspecified", "Inactive", "In Progress", "Completed" }));

        label_department.setText("Department");

        dropdown_department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unspecified", "Copy Room", "Development", "Finishing", "Packing" }));

        label_taskPrice.setText("Price: {task-price}");

        btn_applyChanges.setText("Apply Changes");
        btn_applyChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_applyChangesActionPerformed(evt);
            }
        });

        btn_resetFields.setText("Reset Fields");
        btn_resetFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetFieldsActionPerformed(evt);
            }
        });

        btn_back.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_description)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_jobCode)
                                    .addComponent(label_shelfNo))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_taskPrice)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label_taskId)
                                        .addGap(47, 47, 47)
                                        .addComponent(label_timeStarted)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_department)
                            .addComponent(label_status))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dropdown_status, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dropdown_department, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_applyChanges, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_resetFields, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_back)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_applyChanges, btn_back, btn_resetFields});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_jobCode)
                    .addComponent(label_taskId)
                    .addComponent(label_timeStarted))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_shelfNo)
                    .addComponent(label_taskPrice))
                .addGap(40, 40, 40)
                .addComponent(label_description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_status)
                    .addComponent(dropdown_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resetFields))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_department)
                    .addComponent(dropdown_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_applyChanges))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_back)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resetFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetFieldsActionPerformed
        updateGUI();
    }//GEN-LAST:event_btn_resetFieldsActionPerformed

    private void btn_applyChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_applyChangesActionPerformed
        submitChanges();
    }//GEN-LAST:event_btn_applyChangesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_applyChanges;
    public javax.swing.JButton btn_back;
    private javax.swing.JButton btn_resetFields;
    private javax.swing.JComboBox<String> dropdown_department;
    private javax.swing.JComboBox<String> dropdown_status;
    private javax.swing.JTextArea field_description;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_department;
    private javax.swing.JLabel label_description;
    private javax.swing.JLabel label_jobCode;
    private javax.swing.JLabel label_shelfNo;
    private javax.swing.JLabel label_status;
    private javax.swing.JLabel label_taskId;
    private javax.swing.JLabel label_taskPrice;
    private javax.swing.JLabel label_timeStarted;
    // End of variables declaration//GEN-END:variables
}
